#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""gb-bot - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Openai (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

from __future__ import annotations

import argparse
import asyncio
import os
import re
import sys
import time
import uuid
from collections.abc import Callable
from pathlib import Path
from typing import Any, cast
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

import aiohttp
from dotenv import load_dotenv
from loguru import logger
from pipecat.frames.frames import (
    Frame,
    BotStartedSpeakingFrame,
    BotStoppedSpeakingFrame,
    LLMContextFrame,
    LLMFullResponseEndFrame,
    LLMFullResponseStartFrame,
    LLMMessagesAppendFrame,
    LLMTextFrame,
    OutputTransportMessageUrgentFrame,
    UserStartedSpeakingFrame,
)
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transports.base_transport import BaseTransport
from pipecat.transports.daily.transport import DailyParams, DailyTransport

load_dotenv(override=True)


def configure_logging():
    log_level = os.environ.get("LOG_LEVEL", "INFO").strip().upper() or "INFO"
    logger.remove()
    try:
        logger.add(sys.stderr, level=log_level)
    except ValueError:
        logger.add(sys.stderr, level="INFO")
        logger.warning(f"Invalid LOG_LEVEL={log_level!r}; defaulting to INFO")


configure_logging()

GB_ENV = os.environ.get("GB_ENV", "prod").strip().lower()
API_BASES = {
    "prod": os.environ.get("GB_API_BASE_PROD", "https://api.gradient-bang.com/functions/v1"),
    "local": os.environ.get("GB_API_BASE_LOCAL", "http://127.0.0.1:54321/functions/v1"),
}
API_BASE = API_BASES.get(GB_ENV, API_BASES["prod"]).rstrip("/")
EMAIL = os.environ.get("GB_EMAIL")
PASSWORD = os.environ.get("GB_PASSWORD")
CHARACTER_NAME = os.environ.get("GB_CHARACTER", "HyperionBot")
SYSTEM_PROMPT_PATH = Path(__file__).with_name("system_prompt.md")
TASK_PROMPT_PATH = Path(
    os.environ.get(
        "GB_TASK_PROMPT_PATH",
        Path(__file__).with_name("task_prompts") / "trading.md",
    )
)


def should_log_daily_join_url() -> bool:
    return os.environ.get("GB_LOG_DAILY_JOIN_URL", "").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the Gradient Bang Daily bot.")
    parser.add_argument(
        "--transport",
        choices=["daily"],
        default="daily",
        help="Transport to use. Only daily is currently supported.",
    )
    parser.add_argument(
        "--room-url",
        help="Existing Daily room URL to join instead of creating a new game session.",
    )
    parser.add_argument(
        "--token",
        help="Daily meeting token for --room-url. A t= query param in --room-url is also accepted.",
    )
    parser.add_argument(
        "--audio",
        action="store_true",
        help="Speak via Cartesia TTS like bot-v3. Default is text mode: officer turns are sent as Daily 'user-text-input' app-messages to the Ship AI, with no TTS.",
    )
    args = parser.parse_args(argv)
    if args.token and not args.room_url:
        parser.error("--token requires --room-url")
    return args


def resolve_daily_room(room_url: str, token: str | None = None) -> tuple[str, str | None]:
    """Return a clean Daily room URL and token, extracting t= from the URL when present."""
    parsed_url = urlsplit(room_url)
    query_params = parse_qsl(parsed_url.query, keep_blank_values=True)
    url_tokens = [value for key, value in query_params if key == "t"]

    if url_tokens:
        url_token = url_tokens[-1]
        if token and token != url_token:
            raise ValueError(
                "Daily token was provided by both --token and --room-url?t= with different values"
            )
        token = url_token
        query_params = [(key, value) for key, value in query_params if key != "t"]
        room_url = urlunsplit(
            (
                parsed_url.scheme,
                parsed_url.netloc,
                parsed_url.path,
                urlencode(query_params, doseq=True),
                parsed_url.fragment,
            )
        )

    return room_url, token


def load_system_prompt() -> str:
    prompt_parts = [
        SYSTEM_PROMPT_PATH.read_text().strip(),
        TASK_PROMPT_PATH.read_text().strip(),
    ]
    return "\n\n".join(part for part in prompt_parts if part)


COMMODITIES = (
    ("quantum_foam", "QF"),
    ("retro_organics", "RO"),
    ("neuro_symbolics", "NS"),
)


class GameContextStore:
    """Accumulates useful structured game state from incoming server messages."""

    def __init__(self):
        self._status: str | None = None
        self._ships: str | None = None
        self._map: str | None = None
        self._ports: str | None = None
        self._quests: str | None = None
        self._ui_summary: str | None = None
        self._recent_events: list[str] = []

    def handle_message(self, message: dict[str, Any]):
        if message.get("type") != "server-message":
            return

        data = message.get("data") or {}
        event = data.get("event")
        payload = data.get("payload") or {}
        if not isinstance(event, str) or not isinstance(payload, dict):
            return

        if event in ("status.snapshot", "status.update"):
            self._status = self._log_context_update(event, self._summarize_status(payload))
        elif event == "ships.list":
            self._ships = self._log_context_update(event, self._summarize_ships(payload))
        elif event == "map.local":
            self._map = self._log_context_update(event, self._summarize_map(payload))
        elif event == "ports.list":
            self._ports = self._log_context_update(event, self._summarize_ports(payload))
        elif event == "quest.status":
            self._quests = self._log_context_update(event, self._summarize_quests(payload))
        elif event == "ui-agent-context-summary":
            summary = payload.get("context_summary")
            if isinstance(summary, str) and summary.strip():
                self._ui_summary = self._log_context_update(event, summary.strip())
        elif self._is_recent_event(event):
            self._append_recent_event(event, self._summarize_generic_event(event, payload))

    def render(self) -> str:
        sections = [
            self._status,
            self._ships,
            self._ports,
            self._map,
            self._quests,
            self._format_recent_events(),
            self._format_ui_summary(),
        ]
        body = "\n".join(section for section in sections if section)
        if not body:
            return ""
        return f"Game context from server messages:\n{body}"

    def _log_context_update(self, event: str, summary: str | None) -> str | None:
        if summary:
            logger.debug(f"[GAME CONTEXT][{event}]\n{summary}")
        return summary

    def _append_recent_event(self, event: str, summary: str):
        if summary and (not self._recent_events or self._recent_events[-1] != summary):
            self._recent_events.append(summary)
            self._recent_events = self._recent_events[-6:]
            logger.debug(f"[GAME CONTEXT][{event}]\nRecent events += {summary}")

    def _format_recent_events(self) -> str | None:
        if not self._recent_events:
            return None
        return "Recent events: " + " | ".join(self._recent_events)

    def _format_ui_summary(self) -> str | None:
        if not self._ui_summary:
            return None
        return f"UI summary: {self._ui_summary}"

    def _summarize_status(self, payload: dict[str, Any]) -> str:
        ship = self._dict(payload.get("ship"))
        sector = self._dict(payload.get("sector"))
        player = self._dict(payload.get("player"))
        port = self._dict(sector.get("port"))

        ship_bits = [
            self._clean(ship.get("ship_name")),
            f"type {ship.get('ship_type')}" if ship.get("ship_type") else None,
            f"sector {sector.get('id')}" if sector.get("id") is not None else None,
            self._clean(sector.get("region")),
            self._format_pair("warp", ship.get("warp_power"), ship.get("warp_power_capacity")),
            f"turns/warp {ship.get('turns_per_warp')}" if ship.get("turns_per_warp") else None,
            self._format_pair("shields", ship.get("shields"), ship.get("max_shields")),
            self._format_pair("fighters", ship.get("fighters"), ship.get("max_fighters")),
            f"ship credits {ship.get('credits')}" if ship.get("credits") is not None else None,
            (
                f"bank {player.get('credits_in_bank')}"
                if player.get("credits_in_bank") is not None
                else None
            ),
            self._format_cargo(ship),
        ]

        sector_bits = [
            self._format_port(port),
            self._format_adjacent(sector),
            self._format_presence("players", sector.get("players")),
            self._format_presence("salvage", sector.get("salvage")),
            self._format_garrison(sector.get("garrison")),
        ]

        return self._join_lines(
            "Current status: " + "; ".join(bit for bit in ship_bits if bit),
            "Current sector: " + "; ".join(bit for bit in sector_bits if bit),
        )

    def _summarize_ships(self, payload: dict[str, Any]) -> str | None:
        ships = self._list(payload.get("ships"))
        if not ships:
            return None

        summaries = []
        for ship in ships[:5]:
            if not isinstance(ship, dict):
                continue
            bits = [
                self._clean(ship.get("ship_name")) or self._clean(ship.get("ship_type")),
                f"sector {ship.get('sector')}" if ship.get("sector") is not None else None,
                self._format_pair("warp", ship.get("warp_power"), ship.get("warp_power_capacity")),
                f"credits {ship.get('credits')}" if ship.get("credits") is not None else None,
                self._format_cargo(ship),
                f"task {ship.get('current_task_id')}" if ship.get("current_task_id") else None,
                "destroyed" if ship.get("destroyed_at") else None,
            ]
            summaries.append("; ".join(bit for bit in bits if bit))

        if not summaries:
            return None
        return "Owned ships: " + " | ".join(summaries)

    def _summarize_map(self, payload: dict[str, Any]) -> str | None:
        sectors = self._list(payload.get("sectors"))
        if not sectors:
            return None

        ports = []
        megaports = []
        garrisons = []
        unvisited = []
        one_way_lanes = []
        for sector in sectors:
            if not isinstance(sector, dict):
                continue
            sector_id = sector.get("id")
            hops = sector.get("hops_from_center")
            port = self._dict(sector.get("port"))
            if port:
                label = f"{sector_id} ({hops} hops, {port.get('code')})"
                ports.append(label)
                if port.get("mega"):
                    megaports.append(label)
            if sector.get("garrison"):
                garrisons.append(f"{sector_id} ({hops} hops)")
            if sector.get("visited") is False:
                unvisited.append(f"{sector_id} ({hops} hops)")
            for lane in self._list(sector.get("lanes")):
                if isinstance(lane, dict) and lane.get("two_way") is False:
                    one_way_lanes.append(f"{sector_id}->{lane.get('to')}")

        bits = [
            f"center {payload.get('center_sector')}" if payload.get("center_sector") else None,
            self._format_limited("megaports", megaports, 4),
            self._format_limited("ports", ports, 10),
            self._format_limited("garrisons", garrisons, 5),
            self._format_limited("unvisited", unvisited, 8),
            self._format_limited("one-way lanes", one_way_lanes, 8),
        ]
        return "Local map: " + "; ".join(bit for bit in bits if bit)

    def _summarize_ports(self, payload: dict[str, Any]) -> str | None:
        ports = self._list(payload.get("ports"))
        if not ports:
            return "Known ports: none found."

        summaries = []
        for entry in ports[:12]:
            if not isinstance(entry, dict):
                continue
            sector = self._dict(entry.get("sector"))
            port = self._dict(sector.get("port"))
            if not sector or not port:
                continue
            code = self._clean(port.get("code"))
            mega = " mega" if port.get("mega") else ""
            hops = entry.get("hops_from_start")
            prices = self._dict(port.get("prices"))
            stock = self._dict(port.get("stock"))
            trade = self._format_trade_code(code, prices)
            stock_text = self._format_stock(stock)
            summaries.append(f"{sector.get('id')} ({hops} hops,{mega} {code}): {trade}{stock_text}")

        if not summaries:
            return None
        return "Known ports near current sector: " + " | ".join(summaries)

    def _summarize_quests(self, payload: dict[str, Any]) -> str | None:
        quests = self._list(payload.get("quests"))
        if not quests:
            return "Quests: none active."

        summaries = []
        for quest in quests[:5]:
            if not isinstance(quest, dict):
                continue
            name = self._clean(quest.get("name") or quest.get("code") or quest.get("quest_id"))
            if name:
                summaries.append(name)
        if not summaries:
            return None
        return "Quests: " + "; ".join(summaries)

    def _summarize_generic_event(self, event: str, payload: dict[str, Any]) -> str:
        useful_keys = (
            "status",
            "sector",
            "from_sector",
            "to_sector",
            "commodity",
            "quantity",
            "profit",
            "credits",
            "warp_power",
            "task_id",
            "action",
            "result",
        )
        bits = []
        for key in useful_keys:
            if key in payload and self._is_scalar(payload[key]):
                bits.append(f"{key}={payload[key]}")
        if bits:
            return f"{event}: " + ", ".join(bits)
        return event

    def _is_recent_event(self, event: str) -> bool:
        prefixes = (
            "task.",
            "trade.",
            "movement.",
            "combat.",
            "ship.",
            "bank.",
            "transfer.",
            "recharge.",
            "character.",
        )
        ignored = {"ship.speech_started", "ship.speech_stopped"}
        return event not in ignored and event.startswith(prefixes)

    def _format_port(self, port: dict[str, Any]) -> str | None:
        code = self._clean(port.get("code"))
        if not code:
            return None
        mega = " mega" if port.get("mega") else ""
        return f"port{mega} {code}: {self._format_trade_code(code, self._dict(port.get('prices')))}"

    def _format_trade_code(self, code: str | None, prices: dict[str, Any]) -> str:
        parts = []
        for index, (key, label) in enumerate(COMMODITIES):
            action = code[index] if code and len(code) > index else "?"
            verb = "buys" if action == "B" else "sells" if action == "S" else "has"
            price = prices.get(key)
            parts.append(f"{verb} {label}@{price}" if price is not None else f"{verb} {label}")
        return ", ".join(parts)

    def _format_stock(self, stock: dict[str, Any]) -> str:
        if not stock:
            return ""
        values = []
        for key, label in COMMODITIES:
            if stock.get(key) is not None:
                values.append(f"{label} {stock[key]}")
        return f"; stock {', '.join(values)}" if values else ""

    def _format_cargo(self, ship: dict[str, Any]) -> str | None:
        cargo = self._dict(ship.get("cargo"))
        if not cargo:
            return None
        capacity = ship.get("cargo_capacity")
        empty = ship.get("empty_holds")
        values = [f"{label} {cargo.get(key, 0)}" for key, label in COMMODITIES]
        prefix = f"cargo {', '.join(values)}"
        if capacity is not None:
            prefix += f" / {capacity}"
        if empty is not None:
            prefix += f" ({empty} empty)"
        return prefix

    def _format_adjacent(self, sector: dict[str, Any]) -> str | None:
        adjacent = self._dict(sector.get("adjacent_sectors"))
        if not adjacent:
            return None
        return "adjacent " + ", ".join(str(key) for key in adjacent.keys())

    def _format_garrison(self, garrison: object) -> str | None:
        if not garrison:
            return "no garrison"
        if isinstance(garrison, dict):
            owner = garrison.get("owner_name") or garrison.get("owner") or garrison.get("owner_id")
            mode = garrison.get("mode") or garrison.get("garrison_mode")
            fighters = garrison.get("fighters")
            bits = [
                self._clean(owner),
                self._clean(mode),
                f"fighters {fighters}" if fighters else None,
            ]
            return "garrison " + " ".join(bit for bit in bits if bit)
        return "garrison present"

    def _format_presence(self, label: str, value: object) -> str | None:
        items = self._list(value)
        if not items:
            return f"no {label}"
        return f"{label} present ({len(items)})"

    def _format_pair(self, label: str, current: object, maximum: object) -> str | None:
        if current is None and maximum is None:
            return None
        if maximum is None:
            return f"{label} {current}"
        return f"{label} {current}/{maximum}"

    def _format_limited(self, label: str, values: list[str], limit: int) -> str | None:
        if not values:
            return None
        shown = values[:limit]
        suffix = f" (+{len(values) - limit} more)" if len(values) > limit else ""
        return f"{label}: {', '.join(shown)}{suffix}"

    def _join_lines(self, *lines: str | None) -> str:
        return "\n".join(line for line in lines if line)

    def _dict(self, value: object) -> dict[str, Any]:
        return value if isinstance(value, dict) else {}

    def _list(self, value: object) -> list[Any]:
        return value if isinstance(value, list) else []

    def _clean(self, value: object) -> str | None:
        return value.strip() if isinstance(value, str) and value.strip() else None

    def _is_scalar(self, value: object) -> bool:
        return isinstance(value, str | int | float | bool) or value is None


class GameContextInjector(FrameProcessor):
    """Injects current game context into the latest user message before the LLM."""

    def __init__(self, game_context: GameContextStore):
        super().__init__()
        self._game_context = game_context

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if not isinstance(frame, LLMContextFrame):
            await self.push_frame(frame, direction)
            return

        game_context = self._game_context.render()
        if not game_context:
            await self.push_frame(frame, direction)
            return

        messages: list[Any] = list(frame.context.get_messages())
        last_user_index = self._find_last_user_text_message(messages)
        if last_user_index is None:
            await self.push_frame(frame, direction)
            return

        original = dict(cast(dict[str, Any], messages[last_user_index]))
        original_content = cast(str, original["content"])
        original["content"] = f"{game_context}\n\nMost recent Ship AI speech:\n{original_content}"
        messages[last_user_index] = original

        enriched_context = LLMContext(
            messages=messages,
            tools=frame.context.tools,
            tool_choice=frame.context.tool_choice,
        )
        await self.push_frame(LLMContextFrame(enriched_context), direction)

    def _find_last_user_text_message(self, messages: list[Any]) -> int | None:
        for index in range(len(messages) - 1, -1, -1):
            message = messages[index]
            if not isinstance(message, dict):
                continue
            if message.get("role") == "user" and isinstance(message.get("content"), str):
                return index
        return None


class BotSpeechLogger(FrameProcessor):
    """Logs the bot's streamed LLM response as a single spoken utterance."""

    def __init__(self):
        super().__init__()
        self._parts: list[str] = []

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if isinstance(frame, LLMTextFrame):
            self._parts.append(frame.text)
        elif isinstance(frame, LLMFullResponseEndFrame):
            text = " ".join("".join(self._parts).split())
            if text:
                logger.info(f"[BOT SPEECH] {text}")
            self._parts.clear()

        await self.push_frame(frame, direction)


class WaitTagFilter(FrameProcessor):
    """Suppresses the model's <wait> control response before it reaches TTS."""

    def __init__(self, on_wait: Callable[[], None] | None = None):
        super().__init__()
        self._on_wait = on_wait
        self._parts: list[str] = []

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if isinstance(frame, LLMFullResponseStartFrame):
            self._parts.clear()
            await self.push_frame(frame, direction)
            return

        if isinstance(frame, LLMTextFrame):
            self._parts.append(frame.text)
            return

        if isinstance(frame, LLMFullResponseEndFrame):
            text = "".join(self._parts)
            self._parts.clear()
            if self._is_wait_tag(text):
                logger.info("[BOT WAIT] Suppressing <wait> response while Ship AI task continues")
                if self._on_wait:
                    self._on_wait()
                await self.push_frame(frame, direction)
                return
            if text:
                await self.push_frame(LLMTextFrame(text), direction)
            await self.push_frame(frame, direction)
            return

        await self.push_frame(frame, direction)

    def _is_wait_tag(self, text: str) -> bool:
        normalized = re.sub(r"\s+", "", text.strip().lower())
        return normalized in {"<wait>", "<wait/>", "<wait></wait>"}


class TextModeEmitter(FrameProcessor):
    """Sends each LLM response to the Ship AI as a Daily 'user-text-input'
    app-message instead of running it through TTS. The LLMTextFrame is still
    forwarded so the assistant context aggregator records the response."""

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)
        if isinstance(frame, LLMTextFrame) and direction == FrameDirection.DOWNSTREAM:
            text = (frame.text or "").strip()
            if text:
                # RTVI client-message envelope: outer type is "client-message",
                # inner {t, d} carries the actual handler name + payload.
                msg = {
                    "label": "rtvi-ai",
                    "type": "client-message",
                    "id": uuid.uuid4().hex,
                    "data": {"t": "user-text-input", "d": {"text": text}},
                }
                logger.info(f"[TEXT OUT] -> Ship AI: {text}")
                await self.push_frame(
                    OutputTransportMessageUrgentFrame(message=msg), direction
                )
        await self.push_frame(frame, direction)


class SpeechTimingState:
    def __init__(self):
        self.last_bot_stopped_at: float | None = None
        self.user_speaking = False

    def elapsed_since_bot_stopped(self, now: float, consume: bool = False) -> float | None:
        if self.last_bot_stopped_at is None:
            return None
        elapsed = now - self.last_bot_stopped_at
        if consume:
            self.last_bot_stopped_at = None
        return elapsed

    def reset_for_wait_response(self):
        if self.last_bot_stopped_at is not None:
            logger.info("[SPEECH TIMING] Reset pending bot-stop timer after <wait> response")
        self.last_bot_stopped_at = None
        self.user_speaking = False


class TransportSpeechTimingLogger(FrameProcessor):
    """Logs speech boundary frames at the transport edges for latency measurement."""

    def __init__(self, location: str, timing: SpeechTimingState):
        super().__init__()
        self._location = location
        self._timing = timing

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        now = time.perf_counter()
        if self._is_target_output_frame(frame, direction, BotStoppedSpeakingFrame):
            self._timing.last_bot_stopped_at = now
            self._timing.user_speaking = False
            logger.info(
                f"[SPEECH TIMING] BotStoppedSpeaking after {self._location} "
                f"direction={direction.name}"
            )
        elif self._is_target_input_frame(frame, direction, UserStartedSpeakingFrame):
            self._timing.user_speaking = True
            elapsed = self._timing.elapsed_since_bot_stopped(now, consume=True)
            if elapsed is None:
                logger.info(
                    f"[SPEECH TIMING] UserStartedSpeaking after {self._location} "
                    f"direction={direction.name} elapsed_since_bot_stopped=unknown"
                )
            else:
                logger.info(
                    f"[SPEECH TIMING] UserStartedSpeaking after {self._location} "
                    f"direction={direction.name} elapsed_since_bot_stopped={elapsed:.3f}s"
                )
        elif self._is_target_input_frame(frame, direction, BotStartedSpeakingFrame):
            # Kept visible in case Pipecat emits this unexpectedly for the game side.
            elapsed = self._timing.elapsed_since_bot_stopped(now)
            elapsed_text = "unknown" if elapsed is None else f"{elapsed:.3f}s"
            logger.info(
                f"[SPEECH TIMING] BotStartedSpeaking after {self._location} "
                f"direction={direction.name} elapsed_since_bot_stopped={elapsed_text}"
            )

        await self.push_frame(frame, direction)

    def _is_target_output_frame(
        self,
        frame: Frame,
        direction: FrameDirection,
        frame_type: type[Frame],
    ) -> bool:
        return (
            self._location == "transport output"
            and direction == FrameDirection.DOWNSTREAM
            and isinstance(frame, frame_type)
        )

    def _is_target_input_frame(
        self,
        frame: Frame,
        direction: FrameDirection,
        frame_type: type[Frame],
    ) -> bool:
        return (
            self._location == "transport input"
            and direction == FrameDirection.DOWNSTREAM
            and isinstance(frame, frame_type)
        )


async def api_login(session: aiohttp.ClientSession) -> dict:
    if not EMAIL or not PASSWORD:
        raise RuntimeError("GB_EMAIL and GB_PASSWORD are required unless --room-url is provided")

    async with session.post(
        f"{API_BASE}/login",
        json={"email": EMAIL, "password": PASSWORD},
    ) as response:
        response.raise_for_status()
        return await response.json()


async def api_create_character(
    session: aiohttp.ClientSession,
    token: str,
    name: str,
) -> dict:
    async with session.post(
        f"{API_BASE}/user_character_create",
        json={"name": name},
        headers={"Authorization": f"Bearer {token}"},
    ) as response:
        response.raise_for_status()
        return await response.json()


async def api_start_bot(
    session: aiohttp.ClientSession,
    token: str,
    character_id: str,
) -> dict:
    async with session.post(
        f"{API_BASE}/start",
        json={
            "createDailyRoom": True,
            "dailyRoomProperties": {
                "start_video_off": True,
                "eject_at_room_exp": True,
            },
            "body": {
                "character_id": character_id,
                "bypass_tutorial": True,
            },
        },
        headers={"Authorization": f"Bearer {token}"},
    ) as response:
        response.raise_for_status()
        return await response.json()


async def login_and_start() -> tuple[str, str]:
    """Login, select/create character, start a session, and return Daily credentials."""
    logger.info(f"[1] Logging in ({GB_ENV}, {API_BASE})...")
    async with aiohttp.ClientSession() as session:
        login_data = await api_login(session)
        token = login_data["session"]["access_token"]
        characters = login_data.get("characters", [])
        logger.info(f"    Logged in as {login_data['user']['email']}")

        character_id = None
        for character in characters:
            if character["name"] == CHARACTER_NAME:
                character_id = character["character_id"]
                logger.info(f"    Using character: {CHARACTER_NAME} ({character_id})")
                break

        if not character_id:
            logger.info(f"    Creating character: {CHARACTER_NAME}...")
            result = await api_create_character(session, token, CHARACTER_NAME)
            character_id = result["character_id"]
            logger.info(f"    Created: {character_id}")

        logger.info("[2] Starting game session...")
        start_data = await api_start_bot(session, token, character_id)
        room_url = start_data["dailyRoom"]
        room_token = start_data["dailyToken"]
        session_id = start_data.get("sessionId", "?")
        logger.info(f"    Room: {room_url}")
        if should_log_daily_join_url():
            logger.warning("    Daily join URL logging is enabled; logs will contain a room token")
            logger.info(f"    Join: {room_url}?t={room_token}")
        else:
            logger.info("    Join: redacted (set GB_LOG_DAILY_JOIN_URL=true for local debugging)")
        logger.info(f"    Session: {session_id}")
        return room_url, room_token


async def run_bot(transport: BaseTransport, text_mode: bool = True):
    """Main bot logic.

    text_mode=True (default): send officer turns to Ship AI as Daily
    'user-text-input' app-messages, no Cartesia TTS.
    text_mode=False: classic bot-v3 behavior — speak via Cartesia TTS.
    """
    logger.info(f"Starting bot (mode={'text' if text_mode else 'audio'})")

    output_stage: FrameProcessor
    if text_mode:
        output_stage = TextModeEmitter()
    else:
        output_stage = CartesiaTTSService(
            api_key=os.environ["CARTESIA_API_KEY"],
            settings=CartesiaTTSService.Settings(
                voice=os.getenv("CARTESIA_VOICE_ID", "32b3f3c5-7171-46aa-abe7-b598964aa793"),
            ),
        )

    # LLM service
    llm = OpenAILLMService(
        api_key=os.getenv("OPENAI_API_KEY"),
        settings=OpenAILLMService.Settings(
            model=os.getenv("OPENAI_MODEL", "gpt-4.1"),
            system_instruction=load_system_prompt(),
        ),
    )

    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(context)
    game_context = GameContextStore()
    game_context_injector = GameContextInjector(game_context)
    speech_timing = SpeechTimingState()
    wait_tag_filter = WaitTagFilter(on_wait=speech_timing.reset_for_wait_response)
    bot_speech_logger = BotSpeechLogger()
    transport_input_timing_logger = TransportSpeechTimingLogger(
        "transport input",
        speech_timing,
    )
    transport_output_timing_logger = TransportSpeechTimingLogger(
        "transport output",
        speech_timing,
    )

    # Pipeline - assembled from reusable components. In text mode the TTS
    # stage is replaced by TextModeEmitter, which converts each LLM response
    # into a Daily 'user-text-input' app-message for the Ship AI.
    pipeline = Pipeline(
        [
            transport.input(),
            transport_input_timing_logger,
            user_aggregator,
            # Temporarily disabled: do not append summarized game events to LLM context.
            # game_context_injector,
            llm,
            wait_tag_filter,
            bot_speech_logger,
            output_stage,
            transport.output(),
            transport_output_timing_logger,
            assistant_aggregator,
        ]
    )

    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        enable_rtvi=False,
        observers=[],
    )

    async def send_rtvi(msg_type: str, data: dict | None = None):
        msg: dict[str, object] = {"label": "rtvi-ai", "type": msg_type, "id": uuid.uuid4().hex}
        if data is not None:
            msg["data"] = data
        await task.queue_frames([OutputTransportMessageUrgentFrame(message=msg)])

    class GameTurnBuffer:
        def __init__(self, flush_on_llm_stopped: bool = False):
            # When True (text mode), flush as soon as Ship AI's LLM emits
            # bot-llm-stopped (i.e. response fully generated), without waiting
            # for TTS playback to finish.
            self._flush_on_llm_stopped = flush_on_llm_stopped
            self._reset()

        def _reset(self):
            self._collecting = False
            self._transcriptions: list[str] = []
            self._sentences: list[str] = []
            self._tts_words: list[str] = []
            self._llm_text: list[str] = []
            # In text mode we flush on bot-llm-stopped, but Ship AI keeps
            # emitting bot-output / bot-tts-text as TTS plays out the same
            # response. Block re-accumulation until the next bot-llm-started.
            self._suppressed_until_next_llm = False

        def _ensure_collecting(self):
            if self._suppressed_until_next_llm:
                return False
            if not self._collecting:
                self._reset()
                self._collecting = True
            return True

        def _append_unique(self, items: list[str], text: str):
            text = text.strip()
            if text and (not items or items[-1] != text):
                items.append(text)

        def handle_message(self, message: dict) -> str | None:
            msg_type = message.get("type")
            data = message.get("data") or {}

            if msg_type == "bot-llm-started":
                # New Ship AI response starting; clear any suppression.
                self._reset()
                self._collecting = True
                return None

            if msg_type == "bot-llm-text":
                if not self._ensure_collecting():
                    return None
                chunk = data.get("text", "")
                if chunk:
                    self._llm_text.append(chunk)
                return None

            if msg_type == "bot-llm-stopped" and self._flush_on_llm_stopped:
                flushed = self.flush()
                # Don't re-accumulate TTS fragments that are still in flight
                # for this same Ship AI response.
                self._suppressed_until_next_llm = True
                return flushed

            if msg_type in ("bot-transcription",):
                if not self._ensure_collecting():
                    return None
                self._append_unique(self._transcriptions, data.get("text", ""))
                return None

            if msg_type == "bot-output":
                text = data.get("text", "")
                aggregated_by = data.get("aggregated_by")
                if not self._ensure_collecting():
                    return None
                if aggregated_by == "sentence":
                    self._append_unique(self._sentences, text)
                elif aggregated_by == "word" and data.get("spoken"):
                    self._append_unique(self._tts_words, text)
                return None

            if msg_type == "bot-tts-text":
                if not self._ensure_collecting():
                    return None
                self._append_unique(self._tts_words, data.get("text", ""))
                return None

            if msg_type == "bot-stopped-speaking":
                if self._suppressed_until_next_llm:
                    return None
                return self.flush()

            if msg_type == "server-message" and data.get("event") == "ship.speech_stopped":
                if self._suppressed_until_next_llm:
                    return None
                return self.flush()

            return None

        def flush(self) -> str | None:
            # In text mode, prefer the raw LLM stream — it's available as soon
            # as generation completes, ahead of any TTS playback.
            if self._flush_on_llm_stopped and self._llm_text:
                text = "".join(self._llm_text)
            elif self._transcriptions:
                text = " ".join(self._transcriptions)
            elif self._sentences:
                text = " ".join(self._sentences)
            elif self._llm_text:
                text = "".join(self._llm_text)
            elif self._tts_words:
                text = " ".join(self._tts_words)
                text = re.sub(r"\s+([,.;:!?])", r"\1", text)
            else:
                text = ""

            self._reset()
            text = " ".join(text.split())
            return text or None

    game_turns = GameTurnBuffer(flush_on_llm_stopped=text_mode)

    def log_game_user_speech_boundary(message: dict):
        msg_type = message.get("type")
        data = message.get("data") or {}
        event = data.get("event") if msg_type == "server-message" else None

        if msg_type in ("bot-started-speaking", "bot-output", "bot-tts-text", "bot-transcription"):
            log_game_user_started(f"app_message type={msg_type}")
        elif event == "ship.speech_started":
            log_game_user_started("app_message event=ship.speech_started")
        elif msg_type == "bot-stopped-speaking" or event == "ship.speech_stopped":
            speech_timing.user_speaking = False

    def log_game_user_started(source: str):
        if speech_timing.user_speaking:
            return

        speech_timing.user_speaking = True
        elapsed = speech_timing.elapsed_since_bot_stopped(time.perf_counter(), consume=True)
        elapsed_text = "unknown" if elapsed is None else f"{elapsed:.3f}s"
        logger.info(
            f"[SPEECH TIMING] UserStartedSpeaking from {source} "
            f"elapsed_since_bot_stopped={elapsed_text}"
        )

    async def queue_game_turn(text: str):
        logger.info(f"[GAME TURN] {text}")
        await task.queue_frames(
            [
                LLMMessagesAppendFrame(
                    messages=[{"role": "user", "content": text}],
                    run_llm=True,
                )
            ]
        )

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_app_message")
    async def on_app_message(transport, message, sender):
        logger.debug(f"[APP MESSAGE][{sender}] {message}")
        log_game_user_speech_boundary(message)
        # Temporarily disabled: do not summarize incoming game events for LLM context.
        # game_context.handle_message(message)
        text = game_turns.handle_message(message)
        if text:
            await queue_game_turn(text)

    @transport.event_handler("on_joined")
    async def on_joined(transport, data):
        logger.info("[DAILY] Joined room")
        await asyncio.sleep(2)
        logger.info("[RTVI] Sending client-ready...")
        await send_rtvi("client-ready")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()

    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot():
    """Main bot entry point."""
    args = parse_args()
    if args.room_url:
        try:
            room_url, room_token = resolve_daily_room(args.room_url, args.token)
        except ValueError as exc:
            raise SystemExit(str(exc)) from exc
        logger.info("[1] Joining existing Daily room...")
        logger.info(f"    Room: {room_url}")
        logger.info(f"    Token: {'provided' if room_token else 'none'}")
    else:
        room_url, room_token = await login_and_start()

    text_mode = not args.audio
    transport = DailyTransport(
        room_url,
        room_token,
        "Gradient Bang Player Bot",
        params=DailyParams(
            audio_in_enabled=False,
            audio_out_enabled=not text_mode,
        ),
    )
    await run_bot(transport, text_mode=text_mode)


if __name__ == "__main__":
    asyncio.run(bot())
