#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""gb-bot - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Openai (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

from __future__ import annotations

import asyncio
import os
import re
import uuid

import aiohttp
from dotenv import load_dotenv
from loguru import logger
from pipecat.frames.frames import LLMMessagesAppendFrame, OutputTransportMessageUrgentFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transports.base_transport import BaseTransport
from pipecat.transports.daily.transport import DailyParams, DailyTransport

load_dotenv(override=True)

GB_ENV = os.environ.get("GB_ENV", "prod").strip().lower()
API_BASES = {
    "prod": os.environ.get("GB_API_BASE_PROD", "https://api.gradient-bang.com/functions/v1"),
    "local": os.environ.get("GB_API_BASE_LOCAL", "http://127.0.0.1:54321/functions/v1"),
}
API_BASE = API_BASES.get(GB_ENV, API_BASES["prod"]).rstrip("/")
EMAIL = os.environ["GB_EMAIL"]
PASSWORD = os.environ["GB_PASSWORD"]
CHARACTER_NAME = os.environ.get("GB_CHARACTER", "HyperionBot")


async def api_login(session: aiohttp.ClientSession) -> dict:
    async with session.post(
        f"{API_BASE}/login",
        json={"email": EMAIL, "password": PASSWORD},
    ) as response:
        response.raise_for_status()
        return await response.json()


async def api_create_character(
    session: aiohttp.ClientSession,
    token: str,
    name: str,
) -> dict:
    async with session.post(
        f"{API_BASE}/user_character_create",
        json={"name": name},
        headers={"Authorization": f"Bearer {token}"},
    ) as response:
        response.raise_for_status()
        return await response.json()


async def api_start_bot(
    session: aiohttp.ClientSession,
    token: str,
    character_id: str,
) -> dict:
    async with session.post(
        f"{API_BASE}/start",
        json={
            "createDailyRoom": True,
            "dailyRoomProperties": {
                "start_video_off": True,
                "eject_at_room_exp": True,
            },
            "body": {
                "character_id": character_id,
                "bypass_tutorial": True,
            },
        },
        headers={"Authorization": f"Bearer {token}"},
    ) as response:
        response.raise_for_status()
        return await response.json()


async def login_and_start() -> tuple[str, str]:
    """Login, select/create character, start a session, and return Daily credentials."""
    logger.info(f"[1] Logging in ({GB_ENV}, {API_BASE})...")
    async with aiohttp.ClientSession() as session:
        login_data = await api_login(session)
        token = login_data["session"]["access_token"]
        characters = login_data.get("characters", [])
        logger.info(f"    Logged in as {login_data['user']['email']}")

        character_id = None
        for character in characters:
            if character["name"] == CHARACTER_NAME:
                character_id = character["character_id"]
                logger.info(f"    Using character: {CHARACTER_NAME} ({character_id})")
                break

        if not character_id:
            logger.info(f"    Creating character: {CHARACTER_NAME}...")
            result = await api_create_character(session, token, CHARACTER_NAME)
            character_id = result["character_id"]
            logger.info(f"    Created: {character_id}")

        logger.info("[2] Starting game session...")
        start_data = await api_start_bot(session, token, character_id)
        room_url = start_data["dailyRoom"]
        room_token = start_data["dailyToken"]
        session_id = start_data.get("sessionId", "?")
        logger.info(f"    Room: {room_url}")
        logger.info(f"    Join: {room_url}?t={room_token}")
        logger.info(f"    Session: {session_id}")
        return room_url, room_token


async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Text-to-Speech service
    tts = CartesiaTTSService(
        api_key=os.getenv("CARTESIA_API_KEY"),
        settings=CartesiaTTSService.Settings(
            voice=os.getenv("CARTESIA_VOICE_ID", "71a7ad14-091c-4e8e-a314-022ece01c121"),
        ),
    )

    # LLM service
    llm = OpenAILLMService(
        api_key=os.getenv("OPENAI_API_KEY"),
        settings=OpenAILLMService.Settings(
            model=os.getenv("OPENAI_MODEL", "gpt-4.1"),
            system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can't be spoken. Reply with exactly one short sentence unless the user explicitly asks for more detail.",
        ),
    )

    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(context)

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        enable_rtvi=False,
        observers=[],
    )

    async def send_rtvi(msg_type: str, data: dict | None = None):
        msg = {"label": "rtvi-ai", "type": msg_type, "id": uuid.uuid4().hex}
        if data is not None:
            msg["data"] = data
        await task.queue_frames([OutputTransportMessageUrgentFrame(message=msg)])

    class GameTurnBuffer:
        def __init__(self):
            self._reset()

        def _reset(self):
            self._collecting = False
            self._transcriptions: list[str] = []
            self._sentences: list[str] = []
            self._tts_words: list[str] = []

        def _ensure_collecting(self):
            if not self._collecting:
                self._reset()
                self._collecting = True

        def _append_unique(self, items: list[str], text: str):
            text = text.strip()
            if text and (not items or items[-1] != text):
                items.append(text)

        def handle_message(self, message: dict) -> str | None:
            msg_type = message.get("type")
            data = message.get("data") or {}

            if msg_type in ("bot-transcription",):
                self._ensure_collecting()
                self._append_unique(self._transcriptions, data.get("text", ""))
                return None

            if msg_type == "bot-output":
                text = data.get("text", "")
                aggregated_by = data.get("aggregated_by")
                self._ensure_collecting()
                if aggregated_by == "sentence":
                    self._append_unique(self._sentences, text)
                elif aggregated_by == "word" and data.get("spoken"):
                    self._append_unique(self._tts_words, text)
                return None

            if msg_type == "bot-tts-text":
                self._ensure_collecting()
                self._append_unique(self._tts_words, data.get("text", ""))
                return None

            if msg_type == "bot-stopped-speaking":
                return self.flush()

            if (
                msg_type == "server-message"
                and data.get("event") == "ship.speech_stopped"
            ):
                return self.flush()

            return None

        def flush(self) -> str | None:
            if self._transcriptions:
                text = " ".join(self._transcriptions)
            elif self._sentences:
                text = " ".join(self._sentences)
            elif self._tts_words:
                text = " ".join(self._tts_words)
                text = re.sub(r"\s+([,.;:!?])", r"\1", text)
            else:
                text = ""

            self._reset()
            text = " ".join(text.split())
            return text or None

    game_turns = GameTurnBuffer()

    async def queue_game_turn(text: str):
        logger.info(f"[GAME TURN] {text}")
        await task.queue_frames(
            [
                LLMMessagesAppendFrame(
                    messages=[{"role": "user", "content": text}],
                    run_llm=True,
                )
            ]
        )

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_app_message")
    async def on_app_message(transport, message, sender):
        logger.info(f"[APP MESSAGE][{sender}] {message}")
        text = game_turns.handle_message(message)
        if text:
            await queue_game_turn(text)

    @transport.event_handler("on_joined")
    async def on_joined(transport, data):
        logger.info("[DAILY] Joined room")
        await asyncio.sleep(2)
        logger.info("[RTVI] Sending client-ready...")
        await send_rtvi("client-ready")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()

    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot():
    """Main bot entry point."""
    room_url, room_token = await login_and_start()
    transport = DailyTransport(
        room_url,
        room_token,
        "Pipecat Bot",
        params=DailyParams(
            audio_in_enabled=False,
            audio_out_enabled=True,
        ),
    )
    await run_bot(transport)


if __name__ == "__main__":
    asyncio.run(bot())
